import { ItemIdentifier } from "@serenityjs/core";
import { CategoryBuilder } from "../../../../Classes/Shop/CategoryBuilder";

const ShopSaplingsCategory = new CategoryBuilder({ id: "saplings", display: { name: "Saplings" } })
    .addItem({ id: ItemIdentifier.OakSapling, price: 1250, transactionSound: "random.grass" });

const ShopFlowersCategory = new CategoryBuilder({ id: "flowers", display: { name: "Flowers" } })
    .addItem({ id: ItemIdentifier.Poppy, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.Dandelion, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.BlueOrchid, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.Allium, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.AzureBluet, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.RedTulip, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.OrangeTulip, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.WhiteTulip, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.PinkTulip, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.OxeyeDaisy, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.Cornflower, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.LilyOfTheValley, price: 500, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.PitcherPlant, price: 900, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.Torchflower, price: 900, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.PinkPetals, price: 350, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.CocoaBeans, price: 400, transactionSound: "dig.wood" });

const ShopTerracottaCategory = new CategoryBuilder({ id: "terracotta", display: { name: "Terracotta" } })
    .addItem({ id: ItemIdentifier.WhiteTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.OrangeTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.MagentaTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.LightBlueTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.YellowTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.LimeTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.PinkTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.GrayTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.LightGrayTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.CyanTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.PurpleTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.BlueTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.BrownTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.GreenTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.RedTerracotta, price: 1250, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.BlackTerracotta, price: 1250, transactionSound: "dig.stone" });

const ShopWoolCategory = new CategoryBuilder({ id: "wool", display: { name: "Wool" } })
    .addItem({ id: ItemIdentifier.WhiteWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.OrangeWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.MagentaWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.LightBlueWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.YellowWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.LimeWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.PinkWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.GrayWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.LightGrayWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.CyanWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.PurpleWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.BlueWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.BrownWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.GreenWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.RedWool, price: 750, transactionSound: "dig.cloth" })
    .addItem({ id: ItemIdentifier.BlackWool, price: 750, transactionSound: "dig.cloth" });

const ShopGlassCategory = new CategoryBuilder({ id: "glass", display: { name: "Glass" } })
    .addItem({ id: ItemIdentifier.Glass, price: 500, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.WhiteStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.OrangeStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.MagentaStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.LightBlueStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.YellowStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.LimeStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.PinkStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.GrayStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.LightGrayStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.CyanStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.PurpleStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.BlueStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.BrownStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.GreenStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.RedStainedGlass, price: 750, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.BlackStainedGlass, price: 750, transactionSound: "random.glass" });

const ShopDecorationCategory = new CategoryBuilder({ id: "decoration", display: { name: "Decoration" } })
    .addSubCategory(ShopSaplingsCategory)
    .addSubCategory(ShopFlowersCategory)
    .addSubCategory(ShopTerracottaCategory)
    .addSubCategory(ShopWoolCategory)
    .addSubCategory(ShopGlassCategory)
    .addItem({ id: ItemIdentifier.CraftingTable, price: 400, transactionSound: "dig.wood" })
    .addItem({ id: ItemIdentifier.Chest, price: 1200, transactionSound: "dig.wood" })
    .addItem({ id: ItemIdentifier.Furnace, price: 800, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.BlastFurnace, price: 3600, transactionSound: "dig.stone" })
    .addItem({ id: "minecraft:water", price: 2000, transactionSound: "bucket.empty_water" })
    .addItem({ id: "minecraft:lava", price: 20000, transactionSound: "bucket.empty_lava" })
    .addItem({ id: ItemIdentifier.HayBlock, price: 1800, transactionSound: "dig.grass" })
    .addItem({ id: ItemIdentifier.RedMushroomBlock, price: 1600, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.BrownMushroomBlock, price: 1600, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.RedstoneLamp, price: 1200, transactionSound: "random.glass" })
    .addItem({ id: ItemIdentifier.EndRod, price: 1400, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.DragonEgg, price: 20000000, transactionSound: "dig.stone" })
    .addItem({ id: ItemIdentifier.LightningRod, price: 1200, transactionSound: "dig.copper" })
    .addItem({ id: ItemIdentifier.Bookshelf, price: 1800, transactionSound: "dig.wood" })
    .addItem({ id: ItemIdentifier.ChiseledBookshelf, price: 2700, transactionSound: "break.chiseled_bookshelf" })
    .addItem({ id: ItemIdentifier.Web, price: 800, transactionSound: "break.web" })
    .addItem({ id: ItemIdentifier.Candle, price: 500, transactionSound: "dig.candle" });

export { ShopDecorationCategory };