/** Admin Commands */
import "./Admin/data"
import "./Admin/resetdb"
import "./Admin/cgive"
import "./Admin/rank"
import "./Admin/spawnertest"
import "./Admin/ce"
import "./Admin/tome"
import "./Admin/scroll"
import "./Admin/rot"
import "./Admin/morph"
import "./Admin/stash"
import "./Admin/playeradmin"
import "./Admin/islandadmin"
import "./Admin/money"
import "./Admin/xp"
import "./Admin/uptime"
import "./Admin/setcrate"
import "./Admin/key"

/** Moderation Commands */
import "./Moderation/broadcast"
import "./Moderation/forcerename"

/** General Commands */
import "./General/settings"
import "./General/shop"
import "./General/sellhand"
import "./General/sellhandxp"
import "./General/balance"
import "./General/balancexp"
import "./General/pay"
import "./General/vendor"
import "./General/message"
import "./General/reply"
import "./General/buy"
import "./General/friend"
import "./General/break"
import "./General/discord"
import "./General/guide"
import "./General/topmoney"
import "./General/topxp"

/** Island Commands */
import "./Island/island"

/** Rank Commands */
import "./Rank/fly"
import "./Rank/chatsize"
import "./Rank/sellall"
import "./Rank/sellallxp"
import "./Rank/repair"

/** Enchantment Commands */
import "./Enchantment/merge"
import "./Enchantment/binding"
import "./Enchantment/refine"
import "./Enchantment/master"
import "./Enchantment/expel"
import "./Enchantment/temper"
import "./Enchantment/restore"
import "./Enchantment/celist"